FROM maven:3.6.0-jdk-11-slim AS build
WORKDIR /home
COPY . .
RUN mvn clean package -DskipTests
#
# Package stage
#
FROM openjdk:11-jre-slim
COPY --from=build /home/target/ASAPHub-hub-tester.jar /usr/local/lib/asaphub-tester.jar
EXPOSE 6910
ENTRYPOINT ["java","-jar","/usr/local/lib/asaphub-tester.jar"]